// AgileHarness MCP — onboarding / agent guidance. The remote connector exposes ~48 tools;
// without orientation the consuming agent (Claude on the phone) often can't tell which
// tool to use or how the board works. Two layers fix that, following MCP best practice:
//
//   1. SERVER INSTRUCTIONS (STORYMAP_MCP_INSTRUCTIONS) — passed to createMcpHandler and
//      returned in the `initialize` response, so EVERY client sees them automatically,
//      before any tool call. Kept short: the mental model + the rules + a pointer.
//   2. The `mcp_onboarding` TOOL (ONBOARDING_GUIDE) — the full manual (tool groups + flow
//      recipes + gotchas), fetched on demand. Belt-and-suspenders for clients that don't
//      surface server instructions prominently, and a place for depth the initialize
//      blurb shouldn't carry.
//
// Both share this one source so they never drift. Plain text (no backticks/${} — this is
// a template string).
//
// DEFERRAL IS CLIENT-SIDE (story-26xi3s). When a connector exposes many tools, the Claude
// Code harness (ToolSearch) DEFERS some tool schemas — the agent must tool_search them by
// name before it can call them. There is NO `defer` logic in this server (see register.ts):
// the server cannot "un-defer" a tool. So the lever for discoverability is purely textual —
// NAME the high-use authoring tools (update_card, save_persona, save_system, triage_finding)
// prominently here + in the gate error messages (gates.ts) so an agent finds them despite the
// deferral. The surface must NOT promise to remove a tool from the deferral (it would mislead).

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { defineTool } from "./register";

/** Short, always-on mental model + rules. Loaded via the MCP initialize handshake. */
export const STORYMAP_MCP_INSTRUCTIONS = [
  "AgileHarness MCP — você controla o AgileHarness: um board de User Story Mapping (Jeff Patton) que",
  "é a FONTE DA VERDADE de produto DESTE repositório. Cada app dele tem",
  "um board; os cards percorrem um PIPELINE com GATES e AUTORUN — ao entrar em certos status,",
  "um Claude headless (skill harness-*) processa o card sozinho e o avança.",
  "",
  "PRINCÍPIOS:",
  "1. Leia antes de agir: list_boards → list_cards → get_card. Nunca aja às cegas.",
  "2. Respeite os gates: mover um card para um status sem cumprir o gate é REJEITADO (a tool",
  "   devolve o motivo). Não tente forçar — cumpra o pré-requisito ou rode a skill que o gera.",
  "3. Deixe o autorun trabalhar: para construir uma feature normalmente BASTA create_card com",
  "   um título/escopo claro; a cascata enriquece → quebra → prioriza → … sozinha. Acompanhe",
  "   com runner_status.",
  "4. Texto livre para bug/ideia: use report_issue (sem cardId) — um triador classifica e cria",
  "   1 card na Triagem. Use quando não souber em qual card mexer.",
  "5. INTENÇÃO → TOOL (escolha a superfície de criação certa):",
  "   • plano completo / brain-dump (≥3 itens ou hierarquia activity/step/story) → usm_capture",
  "     (mode:'propose' devolve backbone+stories parenteadas SEM gravar; mode:'apply' grava tudo",
  "     na Triagem). NÃO faça N create_card — isso deixa N stubs órfãos sem hierarquia.",
  "   • um item único e isolado → create_card.",
  "   • bug/ideia em texto livre que não sabe onde encaixar → report_issue.",
  "6. Produção é séria: deploy/kill/delete pedem cuidado e confirmação explícita.",
  "",
  "TOOLS AUTORAIS DE ALTO USO:",
  "   update_card · save_persona · save_system · triage_finding. Este SERVIDOR publica todas as tools",
  "   em tools/list, numa página só — se você fala com ele diretamente, elas já estão aí. O que pode",
  "   escondê-las é o HARNESS DO SEU CLIENTE: alguns deferem o schema quando há muitas, e aí você as",
  "   carrega pelo mecanismo do cliente (no Claude Code, tool_search). Não existe uma tool tool_search",
  "   aqui — procurá-la no servidor é buscar algo que não foi publicado.",
  "   update_card edita os campos AUTORAIS de um card (título, narrativa, aceite, RICE/KANO/funil,",
  "   personas/sistemas, body) — é O CAMINHO para corrigir um card poluído/errado. NÃO recorra",
  "   a tmux/scripts para o que é uma única chamada. NÃO edita `status` (use move_card, que valida o",
  "   gate) nem `tasks` (quem as marca é a skill que fez o trabalho — não há carimbo manual: o gate aceita a",
  "   conclusão real das tasks ou a convergência de conteúdo).",
  "",
  "Grupos de tools: ler board · editar cards · automação (run_skill/runner_status/card_console)",
  "· reportar/triar · código read-only (search_code/read_file) · git/checks/ops · deploy ·",
  "controlar instâncias Claude na VPS (claude_*).",
  "",
  "➜ CHAME A TOOL mcp_onboarding PRIMEIRO (ou em dúvida) para o guia completo com receitas de fluxo.",
].join("\n");

/** Full manual returned by the `mcp_onboarding` tool. */
export const ONBOARDING_GUIDE = [
  "# AgileHarness MCP — Guia do Agente",
  "",
  "## O que é",
  "AgileHarness é um board de User Story Mapping (Jeff Patton) e a FONTE DA VERDADE de produto do",
  "repositório em que ele roda — um board por app. Chame `list_boards` para ver quais existem AQUI.",
  "Cada app tem um board. Os cards têm 3 níveis (activity = objetivo grande · step = tarefa ·",
  "story = história detalhada). Um PIPELINE move cada story por status, com GATES entre eles e",
  "AUTORUN: ao ENTRAR em certos status, um Claude Code headless (a skill harness-* daquela coluna)",
  "processa o card e o avança automaticamente. Card NOVO nasce na Triagem (staging, SEM autorun);",
  "roteado para Enriquecer, o pipeline default vai sozinho até 'Pronta p/ build' e PARA lá (go/no-go)",
  "— não desenha nem escreve código sem você avançar o card.",
  "",
  "## LEIA PRIMEIRO — tools autorais de alto uso",
  "Este servidor publica TODAS as tools em tools/list, numa página só. Se alguma não aparecer para",
  "você, quem a escondeu foi o HARNESS DO SEU CLIENTE: alguns deferem o schema quando há muitas, e o",
  "servidor NÃO consegue 'tirá-las do deferral'. Nesse caso carregue-a pelo mecanismo do cliente (no",
  "Claude Code, tool_search) — não existe uma tool tool_search aqui. As de alto uso:",
  "- update_card — edita os campos AUTORAIS de um card (título, narrativa, aceite, RICE/KANO/funil,",
  "  personas/sistemas, body). É O CAMINHO para corrigir um card poluído ou errado — NÃO use",
  "  tmux/scripts para o que é uma única chamada de update_card. FORA do seu alcance, de propósito:",
  "  `status` (é do move_card, que valida o gate) e `tasks` (a skill que faz o trabalho as marca — não há",
  "  carimbo manual: o gate de evidência aceita a conclusão real das tasks ou a convergência de conteúdo).",
  "- save_persona / save_system — adicionam/editam o vocabulário do board (personas e sistemas).",
  "- triage_finding — marca um finding de code-review (fixed/wontfix/etc.).",
  "",
  "## Princípios de trabalho (siga sempre)",
  "1. O board é a fonte da verdade de produto — leia antes de agir.",
  "2. Liste/leia antes de escrever: list_boards → list_statuses → list_cards → get_card.",
  "3. Respeite os gates: cada status pode exigir um pré-requisito (narrativa+aceite, tasks,",
  "   RICE/KANO/funil, wireframe escolhido, sem blockers, QA verde…). move_card para um status",
  "   sem cumprir o gate é rejeitado COM o motivo — leia e cumpra, não force.",
  "4. Card novo nasce na Triagem (curral barato, sem autorun): roteie-o para Enriquecer e a cascata",
  "   segue sozinha. Prefira deixar o autorun cascatear; use run_skill para disparar manualmente.",
  "5. Para mexer no CÓDIGO real: leia primeiro (search_code/read_file). Para EDITAR código, spawne um",
  "   AGENTE: claude_new({role:'implement', task, board, cardId}) — ele nasce com worktree próprio,",
   "   claim do card e o contrato no prompt. As tools deste MCP não editam código diretamente.",
  "6. Produção/destrutivo (deploy, delete_card, claude_kill, git_commit_push em main) exige",
  "   confirmação explícita e cautela.",
  "7. DOGFOOD — o board `storymap` é EXCEÇÃO: NUNCA deixe o autorun/pipeline (harness-fix/do/review/qa)",
  "   processar cards do PRÓPRIO storymap-ui (a ferramenta/orquestrador). Ela se auto-hospeda, então o",
  "   autorun mexendo nela vira paradoxo (um fix no mecanismo de release COM bug não pode se auto-",
  "   promover por esse mesmo mecanismo). Refatorar/consertar o storymap é SEMPRE numa sessão Claude",
  "   Code dedicada (tmux, --model opus, effort xhigh) guiada passo a passo pelo operador. O campo",
  "   `autorunDisabled: true` no board.yaml do storymap IMPÕE isso no sistema (o autorun nunca dispara",
  "   sozinho lá). Só cards dos boards de PRODUTO correm pelo pipeline normalmente.",
  "",
  "## Ferramentas por grupo",
  "",
  "### 1) Ler o board (COMECE AQUI)",
  "- list_boards — quais boards/apps existem.",
  "- list_statuses — o pipeline de um board (status, gate de cada um, se tem autorun).",
  "- list_cards — cards de um board (filtre por status).",
  "- get_card — os campos de controle de um card (narrativa, aceite, tasks, RICE, findings…); por padrão omite o corpo markdown pesado (passe verbose:true p/ o body completo).",
  "- get_vocabulary — personas, sistemas e releases do board.",
  "",
  "### 2) Criar e editar cards",
  "- INTENÇÃO → TOOL: plano completo/brain-dump (≥3 itens ou hierarquia) → usm_capture · item",
  "  único isolado → create_card · bug/ideia em texto livre sem card → report_issue.",
  "- usm_capture — captura inteligente de um plano completo: mode:'propose' interpreta o texto",
  "  livre e devolve backbone (atividades+steps) + stories parenteadas mapeadas ao vocabulário,",
  "  SEM gravar nada; mode:'apply' grava todos os cards hierarquicamente (entram na Triagem).",
  "  Prefira a N chamadas create_card — estas deixam N stubs órfãos sem pai.",
  "- create_card — UM card isolado na Triagem (o autorun assume depois de roteado p/ Enriquecer).",
  "- update_card — edita campos (título, narrativa, aceite, RICE/KANO/funil, personas…).",
  "- move_card — muda o status (respeita o gate).",
  "- delete_card — remove um card (destrutivo).",
  "",
  "### 3) Automação / pipeline (autorun)",
  "- runner_status — o que está rodando AGORA (runs headless ativos + falhas recentes).",
  "- run_skill — dispara uma skill harness-* num card (ex.: enriquecer/quebrar/priorizar/plan/ux/do/",
  "  review/qa/refine/fix/retire/sync). Use quando quiser rodar um passo manualmente.",
  "- card_console — saída ao vivo / log do run de um card.",
  "- get_card_wireframes / choose_wireframe — ver e escolher a opção de UI (gate de design).",
  "- get_card_plan / get_card_retire_plan — ler o plano técnico / de descontinuação.",
  "",
  "### 4) Reportar e triar",
  "- report_issue — bug/ideia em TEXTO LIVRE, sem cardId: um triador read-only classifica,",
  "  deduplica contra o board e cria 1 card na raia de Triagem. Use quando não souber o card.",
  "- report_bug / refine_card — reabrir um card já entregue para corrigir uma regressão / melhorar.",
  "- discontinue_card / revive_card — descontinuar (remover do app) / reviver um postergado.",
  "- triage_finding — marcar um finding de code-review como fixed/wontfix/etc.",
  "",
  "### 5) Sincronizar com a realidade",
  "- sync_card — reconcilia UM card com o código real (diagnostica o que existe hoje e reposiciona",
  "  o card pelos fatos). Use quando o board parecer desatualizado em relação ao app.",
  "",
  "### 6) Código (read-only)",
  "- search_code — git grep no repo (acha onde está X / quem chama Y).",
  "- read_file — ler um arquivo (trecho por linhas). list_files / file_tree — navegar a estrutura.",
  "",
  "### 7) Git, checks e ops",
  "- git_status / git_diff / git_log / git_show — estado real do repo.",
  "- worktree_list — git worktrees ativos + diagnóstico de órfão (run vazado = merge-back travado) sem abrir terminal.",
  "- run_check — rodar test/validate/lint/typecheck/build (allowlist; nunca deploy/dev).",
  "- query_errors / ops_health — erros de produção (GCP Error Reporting).",
  "- git_commit_push — stage+commit+push (push para main exige confirmMain:true).",
  "- sync_repo — reconcilia o checkout (main) com origin (ff/merge, nunca --force).",
  "- reconcile_stage — reconcilia a branch `stage` (release) com main: 'sync' (seguro) ou 'reset' (destrutivo, confirmReset).",
  "",
  "### 8) Deploy (PRODUÇÃO — guardado)",
  "- deploy_plan (dry-run, sempre antes) → deploy (confirm precisa ser EXATAMENTE o nome do pkg)",
  "  → deploy_status (acompanha; roda em background, leva minutos).",
  "- update_vps / update_status — atualiza a PRÓPRIA VPS (git pull + build + restart) e acompanha.",
  "",
  "### 9) Instâncias Claude na VPS (controle remoto pelo celular)",
  "- claude_sessions — lista os Claude rodando (sessões tmux + processos).",
  "- session_ask — PREFIRA ESTA para falar com uma sessão: manda o texto, ESPERA a resposta e a devolve,",
  "  numa chamada só (no lugar de claude_send + esperar + claude_capture). Diz o `motivo` da parada —",
  "  'aguardando-humano' significa que ela travou num prompt e mandar outra mensagem não adianta.",
  "- session_read — os últimos turnos da conversa, lidos do transcript do CLI (não da tela): ~30x mais",
  "  barato que claude_capture. Devolve um `cursor`; re-chame com sinceLine:<cursor> p/ receber só o novo.",
  "- claude_capture — lê a TELA crua. Use só quando precisar mesmo do terminal (prompt de permissão, TUI,",
  "  sessão que não é Claude) — para acompanhar uma conversa, session_read custa uma fração.",
  "- claude_send — entrega um texto sem esperar resposta. Num SHELL, texto multi-linha exige multiline:true",
  "  (cada linha vira um comando); a sessão MASTER exige confirmMaster:true.",
  "- wait_for_any — pilotando VÁRIAS sessões/cards ao mesmo tempo? Bloqueie NELA (runs + submits +",
  "  sessions) e ela diz QUAL aconteceu primeiro. As esperas de entidade única fazem você voltar a polling.",
  "- claude_new — spawna um AGENTE da frota ({role, task, board?, cardId?}): worktree próprio quando toca",
  "  código, claim do card, modelo pela regra do card. Recusa com a fila/holder quando não dá.",
  "- claude_recycle — troca o processo de um agente com contexto cheio, mantendo árvore/branch/claim.",
  "- claude_kill — encerra uma sessão (não afeta o AgileHarness nem o autorun).",
  "",
  "## Receitas (fluxos comuns)",
  "- Capturar um plano completo pelo chat/celular → usm_capture(board, mode:'propose', text:…) →",
  "  revisar o backbone+stories devolvido → usm_capture(board, mode:'apply', items:[…]). Os cards",
  "  entram na Triagem com a hierarquia preservada (NÃO use N create_card para isso).",
  "- Adicionar uma feature ao app Y → create_card (board=Y, título e escopo claros). O autorun",
  "  cascateia. Acompanhe com runner_status; detalhe com card_console.",
  "- O que está rodando agora? → runner_status (+ card_console <board>/<id> para o log).",
  "- Reportar um bug/ideia que você viu → report_issue com o texto; o triador cria o card.",
  "- Entender o código antes de decidir → search_code → read_file.",
  "- Editar código pelo celular → suggest_work (o que pegar) → claude_new({role:'implement', board, cardId,",
  "  task}) → claude_capture (acompanhar) / claude_send (orientar). O agente integra sozinho pelo train.",
  "- Publicar trabalho feito na VPS → git_commit_push → update_vps.",
  "- Conversar com um Claude que já roda na VPS → claude_sessions (achar a sessão) → session_ask (manda,",
  "  espera e já devolve a resposta). NÃO faça send + sleep + capture: são 3 chamadas e ~10x mais tokens.",
  "- Tocar N sessões em paralelo → dispare todas → wait_for_any({sessions:[…], runs:[…]}) num laço: ele",
  "  devolve QUEM terminou, você trata só aquela, e volta a esperar. É o laço de orquestração de frota.",
  "",
  "## Gotchas",
  "- Gates bloqueiam moves inválidos com o motivo — não é erro do sistema, é o pipeline protegendo.",
  "- Autorun pode estar ON/OFF por coluna; se um card não avança sozinho, a coluna pode ser manual",
  "  (use run_skill).",
  "- IDs são slugs; cada board tem seu próprio vocabulário de status/personas/sistemas (get_vocabulary).",
  "- O AgileHarness roda na VPS via systemd; claude_kill mexe só em sessões tmux, nunca derruba o serviço.",
].join("\n");

export function registerOnboarding(server: McpServer): void {
  defineTool(
    server,
    "mcp_onboarding",
    {
      title: "Onboarding — como usar este MCP",
      description:
        "LEIA PRIMEIRO. Guia completo do AgileHarness para o agente: o que é, o pipeline com gates e " +
        "autorun, TODOS os grupos de ferramentas, receitas de fluxo e princípios de trabalho. Chame no " +
        "início de uma sessão ou sempre que estiver em dúvida sobre qual tool usar e como.",
      inputSchema: {},
    },
    () => ({ content: [{ type: "text", text: ONBOARDING_GUIDE }] }),
  );
}
