import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { findRepoRoot } from "@/lib/storymap/paths";
import { dslToText } from "./to-text";

// O README do artefato AFIRMA, em prosa: "That output is real — generated by the renderer that ships
// in this repository, from the tree above it." Sem este caso, a afirmação é a forma nº1 de defeito
// desta base — capacidade declarada que nenhum teste produz. Um render que mudar de forma (uma
// primitiva nova, uma mudança de largura) deixaria a página publicada mentindo em silêncio, e o
// desenho é justamente o que a página usa para provar que o ASCII vem de CÓDIGO e não de um LLM.
//
// ONDE a página mora é acidente; que o ASCII publicado venha do renderizador é a propriedade. Por
// isso a busca é por CONTEÚDO numa lista curta e explícita de candidatas, e não um caminho fixo: em
// 2026-08-27 o README foi enxugado e a seção de wireframes mudou para `docs/how-it-works.md`, o que
// derrubou este guarda com "o bloco ASCII sumiu do README" — um alarme correto apontando para o
// lugar errado. Cada candidata aparece nas DUAS árvores (no umbrella sob `oss/`, no artefato já na
// raiz), e nenhuma candidata com os blocos REPROVA: um exemplo que deixou de ser publicado não pode
// deixar este arquivo verde por vacuidade.
const CANDIDATAS = ["docs/how-it-works.md", "README.md"] as const;

function paginaDoExemplo(): { caminho: string; md: string } {
  const raiz = findRepoRoot();
  const tentadas: string[] = [];
  for (const rel of CANDIDATAS) {
    for (const abs of [path.join(raiz, "oss", rel), path.join(raiz, rel)]) {
      tentadas.push(abs);
      if (!existsSync(abs)) continue;
      const md = readFileSync(abs, "utf8");
      if (md.includes('```json\n{ "type": "screen"')) return { caminho: abs, md };
    }
  }
  throw new Error(
    `nenhuma página publicada carrega a árvore-fonte do wireframe. Procurei em:\n  ${tentadas.join("\n  ")}\n` +
      `Se o exemplo mudou de arquivo, acrescente o novo caminho a CANDIDATAS; se ele foi REMOVIDO, ` +
      `remova também a prosa que afirma que o ASCII vem do renderizador — a afirmação é o que este guarda cobra.`,
  );
}

describe("o wireframe ASCII do README é o render REAL da árvore que está ao lado dele", () => {
  const { caminho, md } = paginaDoExemplo();

  it("NÃO-VACUIDADE: os dois blocos existem na página", () => {
    expect(md.length, `página vazia (${caminho}) — o caso ficaria verde sem medir`).toBeGreaterThan(500);
    expect(md, `a árvore-fonte sumiu de ${caminho}`).toMatch(/```json\n\{ "type": "screen"/);
    expect(md, `o bloco ASCII sumiu de ${caminho}`).toMatch(/```\n┌─ MOBILE/);
  });

  it("o ASCII publicado bate byte a byte com dslToText(árvore publicada)", () => {
    const json = /```json\n(\{ "type": "screen"[\s\S]*?)\n```/.exec(md)?.[1];
    const ascii = /```\n(┌─ MOBILE[\s\S]*?)\n```/.exec(md)?.[1];
    expect(json, "árvore-fonte não extraída").toBeTruthy();
    expect(ascii, "bloco ASCII não extraído").toBeTruthy();
    expect(
      dslToText(JSON.parse(json as string)),
      "o ASCII do README divergiu do renderizador — a página está afirmando um render que o código " +
        "não produz. Regenere o bloco a partir da árvore, nunca o contrário.",
    ).toBe(ascii);
  });

  it("[CLASSE] a árvore publicada usa primitivas REAIS — um exemplo com tipo inventado não ensina nada", () => {
    const json = /```json\n(\{ "type": "screen"[\s\S]*?)\n```/.exec(md)![1];
    const tipos = new Set<string>();
    const anda = (n: { type?: string; children?: unknown[] }) => {
      if (typeof n.type === "string") tipos.add(n.type);
      for (const c of n.children ?? []) anda(c as never);
    };
    anda(JSON.parse(json));
    expect(tipos.size, "árvore de um nó só — o exemplo não exercita aninhamento").toBeGreaterThanOrEqual(5);
    // Se um tipo não existisse, `dslToText` o descartaria e o caso acima ficaria verde comparando
    // duas saídas igualmente pobres. Aqui cada tipo tem de sobreviver ao coerce do renderizador.
    for (const t of tipos) {
      const so = dslToText({ type: t, props: {}, children: [] } as never);
      expect(so.length, `primitiva "${t}" não renderiza nada — tipo inventado no exemplo do README`).toBeGreaterThan(0);
    }
  });

});
